#pragma once

#define COMBO_STRICT_TIMER
#define COMBO_TERM 30
#define HOLD_ON_OTHER_KEY_PRESS 
#define PERMISSIVE_HOLD 
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U
