#pragma once

#define COMBO_STRICT_TIMER
#define COMBO_TERM 20
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY 
//#define PERMISSIVE_HOLD 
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 350
#define LEADER_NO_TIMEOUT
#define CAPS_WORD_IDLE_TIMEOUT 3000
#define TAPPING_TERM 200
#define QUICK_TAP_TERM 0
